destinations:
  - name: "main_server"
    type: "ftp"
    host: "ftp.example.com"
    user: "user1"
    password: "pass1"
    path: "/test/123"

  - name: "backup_local"
    type: "local"
    path: "D:/backups"

  - name: "remote_scp"
    type: "scp"
    host: "scp.example.com"
    user: "user2"
    password: "pass2"
    path: "/home/user2/backups"

tasks:
  - name: "project_a"
    paths:
      - "/tmp/1"
      - "not found case"
    providers:
      - name: "main_ftp_server"
        type: "ftp"
      - name: "backup_local"
        type: "local"
    timestamped_subfolder: true